### ISSUE TITLE
Change homepage photo

### ISSUE THREAD

**Issue by paragasu** [phisoft/primecare-web#13]
Replace
![image](https://user-images.githubusercontent.com/27353/84854671-d0072900-b094-11ea-95cc-32d0c1285ca7.png)

With
![image](https://user-images.githubusercontent.com/27353/84854682-d7c6cd80-b094-11ea-9a83-745961ff1ceb.png)

**Comment by paragasu** [comment]
better resolution

![94e1430a-c3f3-4aa2-ba15-b9237e7d9758](https://user-images.githubusercontent.com/27353/84857289-46a72500-b09b-11ea-9817-cee32d54e642.JPG)

**Comment by izahshahirah** [comment]
done
