### ISSUE TITLE
Impove UI design

### ISSUE THREAD

**Issue by paragasu** [phisoft/primecare-web#28]
This section look a bit too plain, need to add background etc

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/27353/140009481-aa339c8a-f535-4c48-8ff4-99620aa9df56.png">

**Comment by niksyarul** [comment]
Come up with 2 version (with and without shadow) @paragasu 
![Prime Care Dental Clinic Services(shadow)](https://user-images.githubusercontent.com/90664417/140461745-6619be0e-59bc-4dde-8631-8302ec20739d.png)
![Prime Care Dental Clinic Services](https://user-images.githubusercontent.com/90664417/140461747-95e5b9b6-f128-42d9-a522-be2ca58fa6a0.png)
