### ISSUE TITLE
Add banner similar to phidental

### ISSUE THREAD

**Issue by paragasu** [phisoft/primecare-web#44]
![image](https://user-images.githubusercontent.com/27353/154311928-4e2f1b12-390a-4288-b4a5-b8a53fecf198.png)
![image](https://user-images.githubusercontent.com/27353/154311951-1e4368f8-5eca-480d-a90a-36443fd7fe22.png)

**Comment by rosclaritha** [comment]
![image](https://user-images.githubusercontent.com/30463117/154419909-98d192f9-53bb-4ec6-9e56-cc777785b345.png)
