### ISSUE TITLE
Fix 2nd slide mobile view for iphone12

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/primecare-web#52]
"Provide quality dental care" not center for iphone 12 dimension.
<img width="597" alt="Screenshot 2022-04-01 at 1 23 02 PM" src="https://user-images.githubusercontent.com/30463117/161200073-1f0bb9b2-dc07-42cd-bf8f-a21afd4fe546.png">

**Comment by russel0907** [comment]
Fix 2nd slide mobile view for iphone12;

Firefox dev browser views mobile;
![Screenshot (221)](https://user-images.githubusercontent.com/94702093/161211351-0710dd03-b2a1-444a-b3bb-20f0a2712532.png)

Chrome browser views mobile;
![Screenshot (222)](https://user-images.githubusercontent.com/94702093/161211432-c0b7e19c-850d-465d-a37d-cdf724d775d6.png)

Edge browser views mobile;
![Screenshot (223)](https://user-images.githubusercontent.com/94702093/161211498-c1049487-daf7-44d1-a06d-d54afaf7da89.png)
