### ISSUE TITLE
Remove doctor name from all branches

### ISSUE THREAD

**Issue by paragasu** [phisoft/primecare-web#59]
![WhatsApp Image 2022-06-13 at 11 55 58 AM](https://user-images.githubusercontent.com/27353/173280289-d764222a-cde1-4d36-ace7-204e84e30147.jpeg)

**Comment by russel0907** [comment]
Remove doctor name from all branches;

## branch update
![Screenshot 2022-06-13 at 14-12-15 Prime Care](https://user-images.githubusercontent.com/94702093/173290912-b9c0ad95-f170-467b-a359-de304c13bb38.png)
